In [2]:
import pandas as pd 
root_path = "C:\\Users\\shibiyasaju\\Desktop\\DATA ANALYTICS\\main case study\\Road Accident Analytics and Road Safety Optimization in India"
df = pd.read_csv(f"{root_path}\\data\\csv\\accident_prediction_india.csv")

df.head()

,State Name,City Name,Year,Month,Day of Week,Time of Day,Accident Severity,Number of Vehicles Involved,Vehicle Type Involved,Number of Casualties,...,Road Type,Road Condition,Lighting Conditions,Traffic Control Presence,Speed Limit (km/h),Driver Age,Driver Gender,Driver License Status,Alcohol Involvement,Accident Location Details
0,Jammu and Kashmir,Unknown,2021,May,Monday,1:46,Serious,5,Cycle,0,...,National Highway,Wet,Dark,Signs,61,66,Male,NaN,Yes,Curve
1,Uttar Pradesh,Lucknow,2018,January,Wednesday,21:30,Minor,5,Truck,5,...,Urban Road,Dry,Dusk,Signs,92,60,Male,NaN,Yes,Straight Road
2,Chhattisgarh,Unknown,2023,May,Wednesday,5:37,Minor,5,Pedestrian,6,...,National Highway,Under Construction,Dawn,Signs,120,26,Female,NaN,No,Bridge
3,Uttar Pradesh,Lucknow,2020,June,Saturday,0:31,Minor,3,Bus,10,...,State Highway,Dry,Dark,Signals,76,34,Female,Valid,Yes,Straight Road
4,Sikkim,Unknown,2021,August,Thursday,11:21,Minor,5,Cycle,7,...,Urban Road,Wet,Dusk,Signs,115,30,Male,NaN,No,Intersection

In [3]:
df.columns

Index(['State Name', 'City Name', 'Year', 'Month', 'Day of Week',
       'Time of Day', 'Accident Severity', 'Number of Vehicles Involved',
       'Vehicle Type Involved', 'Number of Casualties', 'Number of Fatalities',
       'Weather Conditions', 'Road Type', 'Road Condition',
       'Lighting Conditions', 'Traffic Control Presence', 'Speed Limit (km/h)',
       'Driver Age', 'Driver Gender', 'Driver License Status',
       'Alcohol Involvement', 'Accident Location Details'],
      dtype='str')

In [4]:
df.shape

(3000, 22)

In [5]:
df['State Name'].value_counts()

State Name
Goa                  109
Sikkim               108
Delhi                108
Uttarakhand          106
Jammu and Kashmir    105
Kerala               102
Tamil Nadu           101
Nagaland             101
Gujarat              100
Puducherry            98
Karnataka             95
Mizoram               95
Uttar Pradesh         94
West Bengal           94
Haryana               94
Jharkhand             94
Rajasthan             93
Odisha                93
Chhattisgarh          92
Meghalaya             92
Telangana             92
Himachal Pradesh      91
Assam                 91
Punjab                90
Maharashtra           89
Andhra Pradesh        88
Manipur               87
Madhya Pradesh        83
Chandigarh            82
Arunachal Pradesh     79
Bihar                 78
Tripura               76
Name: count, dtype: int64

In [6]:
df['City Name'].value_counts()

City Name
Unknown          2138
New Delhi          39
Lucknow            38
Surat              38
Dwarka             38
Mysore             37
Coimbatore         37
Siliguri           35
Udaipur            35
Pune               33
Tirupati           32
Madurai            32
Vadodara           32
Chennai            32
Jodhpur            31
Kolkata            31
Rohini             31
Ahmedabad          30
Bangalore          29
Mangalore          29
Visakhapatnam      29
Kanpur             28
Varanasi           28
Nagpur             28
Mumbai             28
Durgapur           28
Vijayawada         27
Jaipur             27
Name: count, dtype: int64

In [7]:
df['Year'].value_counts()

Year
2020    526
2021    522
2022    521
2023    484
2018    479
2019    468
Name: count, dtype: int64

In [8]:
df['Month'].value_counts()

Month
March        266
June         262
October      261
December     260
January      256
November     250
August       247
May          246
September    240
February     240
July         236
April        236
Name: count, dtype: int64

In [9]:
df['Month'].value_counts()

Month
March        266
June         262
October      261
December     260
January      256
November     250
August       247
May          246
September    240
February     240
July         236
April        236
Name: count, dtype: int64

In [10]:
df['Day of Week'].value_counts()

Day of Week
Wednesday    468
Thursday     438
Monday       427
Friday       423
Sunday       423
Saturday     419
Tuesday      402
Name: count, dtype: int64

In [11]:
df['Accident Severity'].value_counts()

Accident Severity
Minor      1034
Fatal       985
Serious     981
Name: count, dtype: int64

In [12]:
df['Vehicle Type Involved'].value_counts()

Vehicle Type Involved
Truck            449
Auto-Rickshaw    449
Bus              442
Two-Wheeler      427
Cycle            421
Pedestrian       419
Car              393
Name: count, dtype: int64

In [13]:
df['Road Type'].value_counts()

Road Type
State Highway       771
Village Road        768
National Highway    749
Urban Road          712
Name: count, dtype: int64

In [14]:
df['Road Type'].value_counts().head(5)

Road Type
State Highway       771
Village Road        768
National Highway    749
Urban Road          712
Name: count, dtype: int64

In [15]:
df['Weather Conditions'].value_counts()

Weather Conditions
Rainy     631
Stormy    611
Hazy      608
Foggy     576
Clear     574
Name: count, dtype: int64

In [16]:
df['Number of Casualties'].describe()

count    3000.000000
mean        5.066000
std         3.214097
min         0.000000
25%         2.000000
50%         5.000000
75%         8.000000
max        10.000000
Name: Number of Casualties, dtype: float64

In [17]:

df['Time of Day'].head(10)

0     1:46
1    21:30
2     5:37
3     0:31
4    11:21
5      8:4
6    18:55
7    11:40
8     8:26
9      2:1
Name: Time of Day, dtype: str

In [18]:
df[['Weather Conditions',  'Accident Severity']].head()

  Weather Conditions Accident Severity
0               Hazy           Serious
1               Hazy             Minor
2              Foggy             Minor
3              Rainy             Minor
4              Foggy             Minor

In [19]:
pd.crosstab(df['Weather Conditions'], df['Accident Severity'])

Accident Severity   Fatal  Minor  Serious
Weather Conditions
Clear                 190    202      182
Foggy                 195    174      207
Hazy                  200    203      205
Rainy                 197    224      210
Stormy                203    231      177

In [20]:
pd.crosstab(df['Vehicle Type Involved'], df['Accident Severity'])

Accident Severity      Fatal  Minor  Serious
Vehicle Type Involved
Auto-Rickshaw            129    165      155
Bus                      167    130      145
Car                      125    138      130
Cycle                    167    122      132
Pedestrian               134    162      123
Truck                    132    162      155
Two-Wheeler              131    155      141

In [21]:
road_severity = pd.crosstab(
    df['Road Type'],
    df['Accident Severity']
)

road_severity

Accident Severity  Fatal  Minor  Serious
Road Type
National Highway     242    248      259
State Highway        261    252      258
Urban Road           254    252      206
Village Road         228    282      258

In [22]:
df[['State Name', 'Number of Casualties']].head()

          State Name  Number of Casualties
0  Jammu and Kashmir                     0
1      Uttar Pradesh                     5
2       Chhattisgarh                     6
3      Uttar Pradesh                    10
4             Sikkim                     7

In [23]:
state_casualties = df.groupby('State Name')['Number of Casualties'].sum()

state_casualties

State Name
Andhra Pradesh       384
Arunachal Pradesh    365
Assam                449
Bihar                445
Chandigarh           382
Chhattisgarh         441
Delhi                566
Goa                  585
Gujarat              525
Haryana              493
Himachal Pradesh     429
Jammu and Kashmir    499
Jharkhand            493
Karnataka            490
Kerala               520
Madhya Pradesh       461
Maharashtra          468
Manipur              472
Meghalaya            488
Mizoram              460
Nagaland             496
Odisha               441
Puducherry           540
Punjab               412
Rajasthan            501
Sikkim               548
Tamil Nadu           493
Telangana            432
Tripura              398
Uttar Pradesh        479
Uttarakhand          540
West Bengal          503
Name: Number of Casualties, dtype: int64

In [24]:
df[['Year', 'Accident Severity']].head()

   Year Accident Severity
0  2021           Serious
1  2018             Minor
2  2023             Minor
3  2020             Minor
4  2021             Minor

In [25]:
year_month = pd.crosstab(df['Year'], df['Month'])

year_month

Month,April,August,December,February,January,July,June,March,May,November,October,September
Year,,,,,,,,,,,,
2018,40,40,43,31,40,47,49,38,33,33,44,41
2019,29,44,45,32,34,38,39,44,43,35,46,39
2020,44,42,50,43,53,37,42,46,41,39,49,40
2021,48,39,48,46,40,34,52,39,52,45,34,45
2022,39,41,35,46,52,39,43,48,45,52,43,38
2023,36,41,39,42,37,41,37,51,32,46,45,37

In [26]:
day_severity = pd.crosstab(
    df['Day of Week'],
    df['Accident Severity']
)

day_severity

Accident Severity  Fatal  Minor  Serious
Day of Week
Friday               118    159      146
Monday               146    141      140
Saturday             140    143      136
Sunday               129    145      149
Thursday             144    154      140
Tuesday              144    149      109
Wednesday            164    143      161

In [27]:
vehicle_casualties = df.groupby('Vehicle Type Involved')['Number of Casualties'].sum()

vehicle_casualties

Vehicle Type Involved
Auto-Rickshaw    2304
Bus              2266
Car              2046
Cycle            2091
Pedestrian       2089
Truck            2262
Two-Wheeler      2140
Name: Number of Casualties, dtype: int64

In [28]:
weather_casualties = df.groupby('Weather Conditions')['Number of Casualties'].mean()

weather_casualties

Weather Conditions
Clear     4.947735
Foggy     5.057292
Hazy      5.116776
Rainy     5.052298
Stormy    5.148936
Name: Number of Casualties, dtype: float64

In [29]:
road_casualties = (
    df.groupby('Road Type')['Number of Casualties']
      .sum()
      .sort_values(ascending=False)
)

road_casualties

Road Type
National Highway    3898
State Highway       3864
Village Road        3823
Urban Road          3613
Name: Number of Casualties, dtype: int64

In [30]:
state_severity = pd.crosstab(
    df['State Name'],
    df['Accident Severity']
)

state_severity

Accident Severity  Fatal  Minor  Serious
State Name
Andhra Pradesh        32     31       25
Arunachal Pradesh     28     24       27
Assam                 29     28       34
Bihar                 30     25       23
Chandigarh            17     32       33
Chhattisgarh          30     32       30
Delhi                 31     35       42
Goa                   40     42       27
Gujarat               32     36       32
Haryana               24     39       31
Himachal Pradesh      25     38       28
Jammu and Kashmir     35     26       44
Jharkhand             27     32       35
Karnataka             33     34       28
Kerala                40     26       36
Madhya Pradesh        28     26       29
Maharashtra           35     26       28
Manipur               30     30       27
Meghalaya             28     34       30
Mizoram               34     27       34
Nagaland              39     36       26
Odisha                25     36       32
Puducherry            35     38       25
Punjab                28     32       30
Rajasthan             30     33       30
Sikkim                29     38       41
Tamil Nadu            38     36       27
Telangana             29     34       29
Tripura               22     24       30
Uttar Pradesh         29     37       28
Uttarakhand           37     40       29
West Bengal           36     27       31

In [31]:
df['Time'] = pd.to_datetime(
    df['Time of Day'],
    format='%H:%M',
    errors='coerce'
)

df.head()

,State Name,City Name,Year,Month,Day of Week,Time of Day,Accident Severity,Number of Vehicles Involved,Vehicle Type Involved,Number of Casualties,...,Road Condition,Lighting Conditions,Traffic Control Presence,Speed Limit (km/h),Driver Age,Driver Gender,Driver License Status,Alcohol Involvement,Accident Location Details,Time
0,Jammu and Kashmir,Unknown,2021,May,Monday,1:46,Serious,5,Cycle,0,...,Wet,Dark,Signs,61,66,Male,NaN,Yes,Curve,1900-01-01 01:46:00
1,Uttar Pradesh,Lucknow,2018,January,Wednesday,21:30,Minor,5,Truck,5,...,Dry,Dusk,Signs,92,60,Male,NaN,Yes,Straight Road,1900-01-01 21:30:00
2,Chhattisgarh,Unknown,2023,May,Wednesday,5:37,Minor,5,Pedestrian,6,...,Under Construction,Dawn,Signs,120,26,Female,NaN,No,Bridge,1900-01-01 05:37:00
3,Uttar Pradesh,Lucknow,2020,June,Saturday,0:31,Minor,3,Bus,10,...,Dry,Dark,Signals,76,34,Female,Valid,Yes,Straight Road,1900-01-01 00:31:00
4,Sikkim,Unknown,2021,August,Thursday,11:21,Minor,5,Cycle,7,...,Wet,Dusk,Signs,115,30,Male,NaN,No,Intersection,1900-01-01 11:21:00

In [32]:
lighting_condition_severity = pd.crosstab(
    df['Lighting Conditions'],
    df['Accident Severity']
)

lighting_condition_severity

Accident Severity    Fatal  Minor  Serious
Lighting Conditions
Dark                   254    259      250
Dawn                   221    256      248
Daylight               262    252      239
Dusk                   248    267      244

In [36]:

Number_of_Casualties_severity = pd.crosstab(
    df['Number of Casualties'],
    df['Accident Severity']
)

Number_of_Casualties_severity

Accident Severity     Fatal  Minor  Serious
Number of Casualties
0                        85     96       89
1                        91    105       89
2                        97    107       79
3                        94     75       82
4                        73     86       81
5                        91     95       96
6                        81     72       99
7                        82     97       76
8                        97     96      111
9                        91    110       84
10                      103     95       95

In [38]:

Alcohol_Involvement_severity = pd.crosstab(
    df['Alcohol Involvement'],
    df['Accident Severity']
)



Alcohol_Involvement_severity

Accident Severity    Fatal  Minor  Serious
Alcohol Involvement
No                     484    522      474
Yes                    501    512      507

In [39]:


Driver_Age_Severity = pd.crosstab(
    df['Driver Age'],
    df['Accident Severity']
)

Driver_Age_Severity

Accident Severity  Fatal  Minor  Serious
Driver Age
18                    20     22       27
19                    18     26       20
20                    22     13       16
21                    14     25       19
22                    18     17       17
23                    21     23       19
24                    21     22       17
25                    17     20       19
26                    14     17       19
27                    21     20       22
28                    21     19       16
29                    15     21       17
30                    17     23       13
31                    22     11       16
32                    13     16       17
33                    14     22       13
34                    15     14       19
35                    19     16       17
36                     9     18       16
37                    17     23       22
38                    20     17       18
39                    21     14       21
40                    24     21       13
41                    14     12       16
42                    17     15       16
43                    20     22       23
44                    21     20       24
45                    19     22       26
46                    14     18       24
47                    22     19       19
48                    17     22       26
49                    20     19       16
50                    19     18       24
51                    25     17       19
52                    20     14       21
53                    16     21       19
54                    21     23       19
55                    21     16       16
56                    22     20       24
57                    17     21       12
58                    19     24       16
59                    25     19       15
60                    14     23       22
61                    20     20       15
62                    23     23       15
63                    28     13       17
64                    23     21       16
65                    14     16       12
66                    14     21       17
67                    22     25       20
68                    15     13       28
69                    13     24       17
70                    17     33       14

In [43]:
Driver_Age_Severity = (
    df.groupby('Driver Age')['Number of Casualties']
      .sum()
      .sort_values(ascending=False)
)

Driver_Age_Severity

Driver Age
18    69
67    67
45    67
56    66
43    65
48    65
44    65
19    64
70    64
54    63
23    63
27    63
37    62
51    61
50    61
62    61
24    60
64    60
47    60
58    59
60    59
59    59
63    58
21    58
40    58
39    56
46    56
53    56
68    56
25    56
28    56
52    55
38    55
61    55
49    55
69    54
29    53
55    53
30    53
22    52
66    52
35    52
20    51
57    50
26    50
31    49
33    49
34    48
42    48
32    46
36    43
41    42
65    42
Name: Accident Severity, dtype: int64

In [51]:

Driver_License_Status_Severity =  pd.crosstab(
    df['Driver License Status'],
    df['Accident Severity']
)


Driver_License_Status_Severity

Accident Severity      Fatal  Minor  Serious
Driver License Status
Expired                  319    339      310
Valid                    354    368      335

In [53]:

Accident_Location_Details_Severity =  pd.crosstab(
    df['Accident Location Details'],
    df['Accident Severity']
)

Accident_Location_Details_Severity

Accident Severity          Fatal  Minor  Serious
Accident Location Details
Bridge                       256    261      248
Curve                        221    245      240
Intersection                 259    274      256
Straight Road                249    254      237