In [ ]:
import pandas as pd 
root_path = "C:\\Users\\shibiyasaju\\Desktop\\DATA ANALYTICS\\main case study\\Road Accident Analytics and Road Safety Optimization in India"
df = pd.read_csv(f"{root_path}\\data\\csv\\accident_prediction_india.csv")

print(df.head())
df.head()

          State Name City Name  Year    Month Day of Week Time of Day  \
0  Jammu and Kashmir   Unknown  2021      May      Monday        1:46
1      Uttar Pradesh   Lucknow  2018  January   Wednesday       21:30
2       Chhattisgarh   Unknown  2023      May   Wednesday        5:37
3      Uttar Pradesh   Lucknow  2020     June    Saturday        0:31
4             Sikkim   Unknown  2021   August    Thursday       11:21

  Accident Severity  Number of Vehicles Involved Vehicle Type Involved  \
0           Serious                            5                 Cycle
1             Minor                            5                 Truck
2             Minor                            5            Pedestrian
3             Minor                            3                   Bus
4             Minor                            5                 Cycle

   Number of Casualties  ...         Road Type      Road Condition  \
0                     0  ...  National Highway                 Wet
1                     5  ...        Urban Road                 Dry
2                     6  ...  National Highway  Under Construction
3                    10  ...     State Highway                 Dry
4                     7  ...        Urban Road                 Wet

  Lighting Conditions Traffic Control Presence Speed Limit (km/h) Driver Age  \
0                Dark                    Signs                 61         66
1                Dusk                    Signs                 92         60
2                Dawn                    Signs                120         26
3                Dark                  Signals                 76         34
4                Dusk                    Signs                115         30

   Driver Gender  Driver License Status Alcohol Involvement  \
0           Male                    NaN                 Yes
1           Male                    NaN                 Yes
2         Female                    NaN                  No
3         Female                  Valid                 Yes
4           Male                    NaN                  No

  Accident Location Details
0                     Curve
1             Straight Road
2                    Bridge
3             Straight Road
4              Intersection

[5 rows x 22 columns]

In [4]:
df.shape
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 3000
Columns: 22

In [5]:
df.columns

Index(['State Name', 'City Name', 'Year', 'Month', 'Day of Week',
       'Time of Day', 'Accident Severity', 'Number of Vehicles Involved',
       'Vehicle Type Involved', 'Number of Casualties', 'Number of Fatalities',
       'Weather Conditions', 'Road Type', 'Road Condition',
       'Lighting Conditions', 'Traffic Control Presence', 'Speed Limit (km/h)',
       'Driver Age', 'Driver Gender', 'Driver License Status',
       'Alcohol Involvement', 'Accident Location Details'],
      dtype='str')

In [6]:
df.head()

,State Name,City Name,Year,Month,Day of Week,Time of Day,Accident Severity,Number of Vehicles Involved,Vehicle Type Involved,Number of Casualties,...,Road Type,Road Condition,Lighting Conditions,Traffic Control Presence,Speed Limit (km/h),Driver Age,Driver Gender,Driver License Status,Alcohol Involvement,Accident Location Details
0,Jammu and Kashmir,Unknown,2021,May,Monday,1:46,Serious,5,Cycle,0,...,National Highway,Wet,Dark,Signs,61,66,Male,NaN,Yes,Curve
1,Uttar Pradesh,Lucknow,2018,January,Wednesday,21:30,Minor,5,Truck,5,...,Urban Road,Dry,Dusk,Signs,92,60,Male,NaN,Yes,Straight Road
2,Chhattisgarh,Unknown,2023,May,Wednesday,5:37,Minor,5,Pedestrian,6,...,National Highway,Under Construction,Dawn,Signs,120,26,Female,NaN,No,Bridge
3,Uttar Pradesh,Lucknow,2020,June,Saturday,0:31,Minor,3,Bus,10,...,State Highway,Dry,Dark,Signals,76,34,Female,Valid,Yes,Straight Road
4,Sikkim,Unknown,2021,August,Thursday,11:21,Minor,5,Cycle,7,...,Urban Road,Wet,Dusk,Signs,115,30,Male,NaN,No,Intersection

In [7]:
df.head(10)

,State Name,City Name,Year,Month,Day of Week,Time of Day,Accident Severity,Number of Vehicles Involved,Vehicle Type Involved,Number of Casualties,...,Road Type,Road Condition,Lighting Conditions,Traffic Control Presence,Speed Limit (km/h),Driver Age,Driver Gender,Driver License Status,Alcohol Involvement,Accident Location Details
0,Jammu and Kashmir,Unknown,2021,May,Monday,1:46,Serious,5,Cycle,0,...,National Highway,Wet,Dark,Signs,61,66,Male,NaN,Yes,Curve
1,Uttar Pradesh,Lucknow,2018,January,Wednesday,21:30,Minor,5,Truck,5,...,Urban Road,Dry,Dusk,Signs,92,60,Male,NaN,Yes,Straight Road
2,Chhattisgarh,Unknown,2023,May,Wednesday,5:37,Minor,5,Pedestrian,6,...,National Highway,Under Construction,Dawn,Signs,120,26,Female,NaN,No,Bridge
3,Uttar Pradesh,Lucknow,2020,June,Saturday,0:31,Minor,3,Bus,10,...,State Highway,Dry,Dark,Signals,76,34,Female,Valid,Yes,Straight Road
4,Sikkim,Unknown,2021,August,Thursday,11:21,Minor,5,Cycle,7,...,Urban Road,Wet,Dusk,Signs,115,30,Male,NaN,No,Intersection
5,Meghalaya,Unknown,2020,November,Tuesday,8:4,Serious,1,Truck,6,...,Village Road,Dry,Daylight,Police Checkpost,48,44,Male,Expired,Yes,Bridge
6,Sikkim,Unknown,2021,October,Monday,18:55,Fatal,2,Two-Wheeler,9,...,Urban Road,Under Construction,Dusk,Police Checkpost,111,48,Female,NaN,No,Straight Road
7,Himachal Pradesh,Unknown,2022,December,Wednesday,11:40,Minor,3,Truck,1,...,State Highway,Damaged,Dark,Police Checkpost,62,42,Female,Valid,No,Curve
8,Rajasthan,Jodhpur,2021,July,Saturday,8:26,Fatal,3,Truck,7,...,Urban Road,Damaged,Dawn,Signs,35,53,Male,Valid,No,Straight Road
9,Rajasthan,Jodhpur,2018,August,Saturday,2:1,Fatal,2,Car,3,...,State Highway,Under Construction,Dark,Signs,110,50,Female,NaN,Yes,Straight Road

In [8]:
df.tail()

,State Name,City Name,Year,Month,Day of Week,Time of Day,Accident Severity,Number of Vehicles Involved,Vehicle Type Involved,Number of Casualties,...,Road Type,Road Condition,Lighting Conditions,Traffic Control Presence,Speed Limit (km/h),Driver Age,Driver Gender,Driver License Status,Alcohol Involvement,Accident Location Details
2995,Tamil Nadu,Chennai,2021,January,Sunday,1:15,Minor,5,Truck,4,...,National Highway,Wet,Dark,Signs,74,43,Male,Expired,Yes,Intersection
2996,Uttarakhand,Unknown,2018,July,Sunday,10:12,Fatal,3,Car,3,...,Urban Road,Under Construction,Daylight,NaN,86,23,Female,NaN,Yes,Intersection
2997,Meghalaya,Unknown,2021,January,Thursday,19:34,Minor,2,Two-Wheeler,8,...,National Highway,Dry,Dark,Signs,47,57,Female,Valid,Yes,Intersection
2998,Meghalaya,Unknown,2023,June,Sunday,20:54,Fatal,1,Cycle,9,...,Urban Road,Under Construction,Daylight,Signs,60,28,Female,Expired,Yes,Bridge
2999,Arunachal Pradesh,Unknown,2020,September,Monday,7:19,Fatal,5,Cycle,1,...,National Highway,Under Construction,Daylight,NaN,40,66,Male,NaN,Yes,Bridge

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   State Name                   3000 non-null   str
 1   City Name                    3000 non-null   str
 2   Year                         3000 non-null   int64
 3   Month                        3000 non-null   str
 4   Day of Week                  3000 non-null   str
 5   Time of Day                  3000 non-null   str
 6   Accident Severity            3000 non-null   str
 7   Number of Vehicles Involved  3000 non-null   int64
 8   Vehicle Type Involved        3000 non-null   str
 9   Number of Casualties         3000 non-null   int64
 10  Number of Fatalities         3000 non-null   int64
 11  Weather Conditions           3000 non-null   str
 12  Road Type                    3000 non-null   str
 13  Road Condition               3000 non-null   str
 14  Lighting Conditions          3000 non-null   str
 15  Traffic Control Presence     2284 non-null   str
 16  Speed Limit (km/h)           3000 non-null   int64
 17  Driver Age                   3000 non-null   int64
 18  Driver Gender                3000 non-null   str
 19  Driver License Status        2025 non-null   str
 20  Alcohol Involvement          3000 non-null   str
 21  Accident Location Details    3000 non-null   str
dtypes: int64(6), str(16)
memory usage: 515.8 KB

In [10]:
df.describe()

,Year,Number of Vehicles Involved,Number of Casualties,Number of Fatalities,Speed Limit (km/h),Driver Age
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000
mean,2020.530000,2.996000,5.066000,2.455333,74.940667,44.17700
std,1.683858,1.428285,3.214097,1.717650,26.765088,15.40286
min,2018.000000,1.000000,0.000000,0.000000,30.000000,18.00000
25%,2019.000000,2.000000,2.000000,1.000000,51.000000,31.00000
50%,2021.000000,3.000000,5.000000,2.000000,75.000000,45.00000
75%,2022.000000,4.000000,8.000000,4.000000,99.000000,57.00000
max,2023.000000,5.000000,10.000000,5.000000,120.000000,70.00000

In [11]:
df.describe(include='all')

,State Name,City Name,Year,Month,Day of Week,Time of Day,Accident Severity,Number of Vehicles Involved,Vehicle Type Involved,Number of Casualties,...,Road Type,Road Condition,Lighting Conditions,Traffic Control Presence,Speed Limit (km/h),Driver Age,Driver Gender,Driver License Status,Alcohol Involvement,Accident Location Details
count,3000,3000,3000.000000,3000,3000,3000,3000,3000.000000,3000,3000.000000,...,3000,3000,3000,2284,3000.000000,3000.00000,3000,2025,3000,3000
unique,32,28,NaN,12,7,1263,3,NaN,7,NaN,...,4,4,4,3,NaN,NaN,2,2,2,4
top,Goa,Unknown,NaN,March,Wednesday,3:40,Minor,NaN,Truck,NaN,...,State Highway,Under Construction,Dark,Signs,NaN,NaN,Female,Valid,Yes,Intersection
freq,109,2138,NaN,266,468,7,1034,NaN,449,NaN,...,771,778,763,812,NaN,NaN,1563,1057,1520,789
mean,NaN,NaN,2020.530000,NaN,NaN,NaN,NaN,2.996000,NaN,5.066000,...,NaN,NaN,NaN,NaN,74.940667,44.17700,NaN,NaN,NaN,NaN
std,NaN,NaN,1.683858,NaN,NaN,NaN,NaN,1.428285,NaN,3.214097,...,NaN,NaN,NaN,NaN,26.765088,15.40286,NaN,NaN,NaN,NaN
min,NaN,NaN,2018.000000,NaN,NaN,NaN,NaN,1.000000,NaN,0.000000,...,NaN,NaN,NaN,NaN,30.000000,18.00000,NaN,NaN,NaN,NaN
25%,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN,2.000000,NaN,2.000000,...,NaN,NaN,NaN,NaN,51.000000,31.00000,NaN,NaN,NaN,NaN
50%,NaN,NaN,2021.000000,NaN,NaN,NaN,NaN,3.000000,NaN,5.000000,...,NaN,NaN,NaN,NaN,75.000000,45.00000,NaN,NaN,NaN,NaN
75%,NaN,NaN,2022.000000,NaN,NaN,NaN,NaN,4.000000,NaN,8.000000,...,NaN,NaN,NaN,NaN,99.000000,57.00000,NaN,NaN,NaN,NaN
max,NaN,NaN,2023.000000,NaN,NaN,NaN,NaN,5.000000,NaN,10.000000,...,NaN,NaN,NaN,NaN,120.000000,70.00000,NaN,NaN,NaN,NaN

In [12]:
df.dtypes

State Name                       str
City Name                        str
Year                           int64
Month                            str
Day of Week                      str
Time of Day                      str
Accident Severity                str
Number of Vehicles Involved    int64
Vehicle Type Involved            str
Number of Casualties           int64
Number of Fatalities           int64
Weather Conditions               str
Road Type                        str
Road Condition                   str
Lighting Conditions              str
Traffic Control Presence         str
Speed Limit (km/h)             int64
Driver Age                     int64
Driver Gender                    str
Driver License Status            str
Alcohol Involvement              str
Accident Location Details        str
dtype: object

In [13]:
df.isnull().sum()

State Name                       0
City Name                        0
Year                             0
Month                            0
Day of Week                      0
Time of Day                      0
Accident Severity                0
Number of Vehicles Involved      0
Vehicle Type Involved            0
Number of Casualties             0
Number of Fatalities             0
Weather Conditions               0
Road Type                        0
Road Condition                   0
Lighting Conditions              0
Traffic Control Presence       716
Speed Limit (km/h)               0
Driver Age                       0
Driver Gender                    0
Driver License Status          975
Alcohol Involvement              0
Accident Location Details        0
dtype: int64

In [14]:
missing_percentage = df.isnull().mean() * 100

print(missing_percentage)

State Name                      0.000000
City Name                       0.000000
Year                            0.000000
Month                           0.000000
Day of Week                     0.000000
Time of Day                     0.000000
Accident Severity               0.000000
Number of Vehicles Involved     0.000000
Vehicle Type Involved           0.000000
Number of Casualties            0.000000
Number of Fatalities            0.000000
Weather Conditions              0.000000
Road Type                       0.000000
Road Condition                  0.000000
Lighting Conditions             0.000000
Traffic Control Presence       23.866667
Speed Limit (km/h)              0.000000
Driver Age                      0.000000
Driver Gender                   0.000000
Driver License Status          32.500000
Alcohol Involvement             0.000000
Accident Location Details       0.000000
dtype: float64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df[df.duplicated()]

Empty DataFrame
Columns: [State Name, City Name, Year, Month, Day of Week, Time of Day, Accident Severity, Number of Vehicles Involved, Vehicle Type Involved, Number of Casualties, Number of Fatalities, Weather Conditions, Road Type, Road Condition, Lighting Conditions, Traffic Control Presence, Speed Limit (km/h), Driver Age, Driver Gender, Driver License Status, Alcohol Involvement, Accident Location Details]
Index: []

[0 rows x 22 columns]

In [17]:
df = df.drop_duplicates()

In [18]:
df['State Name'].unique()

<StringArray>
['Jammu and Kashmir',     'Uttar Pradesh',      'Chhattisgarh',
            'Sikkim',         'Meghalaya',  'Himachal Pradesh',
         'Rajasthan',             'Assam',             'Bihar',
         'Telangana', 'Arunachal Pradesh',    'Andhra Pradesh',
         'Karnataka',    'Madhya Pradesh',        'Puducherry',
       'Maharashtra',        'Tamil Nadu',        'Chandigarh',
           'Gujarat',            'Odisha',       'West Bengal',
            'Kerala',          'Nagaland',           'Tripura',
       'Uttarakhand',           'Haryana',               'Goa',
           'Mizoram',             'Delhi',         'Jharkhand',
            'Punjab',           'Manipur']
Length: 32, dtype: str

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.describe()

,Year,Number of Vehicles Involved,Number of Casualties,Number of Fatalities,Speed Limit (km/h),Driver Age
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000
mean,2020.530000,2.996000,5.066000,2.455333,74.940667,44.17700
std,1.683858,1.428285,3.214097,1.717650,26.765088,15.40286
min,2018.000000,1.000000,0.000000,0.000000,30.000000,18.00000
25%,2019.000000,2.000000,2.000000,1.000000,51.000000,31.00000
50%,2021.000000,3.000000,5.000000,2.000000,75.000000,45.00000
75%,2022.000000,4.000000,8.000000,4.000000,99.000000,57.00000
max,2023.000000,5.000000,10.000000,5.000000,120.000000,70.00000

In [21]:
df.isnull().sum()

State Name                       0
City Name                        0
Year                             0
Month                            0
Day of Week                      0
Time of Day                      0
Accident Severity                0
Number of Vehicles Involved      0
Vehicle Type Involved            0
Number of Casualties             0
Number of Fatalities             0
Weather Conditions               0
Road Type                        0
Road Condition                   0
Lighting Conditions              0
Traffic Control Presence       716
Speed Limit (km/h)               0
Driver Age                       0
Driver Gender                    0
Driver License Status          975
Alcohol Involvement              0
Accident Location Details        0
dtype: int64

In [22]:
df.nunique()

State Name                       32
City Name                        28
Year                              6
Month                            12
Day of Week                       7
Time of Day                    1263
Accident Severity                 3
Number of Vehicles Involved       5
Vehicle Type Involved             7
Number of Casualties             11
Number of Fatalities              6
Weather Conditions                5
Road Type                         4
Road Condition                    4
Lighting Conditions               4
Traffic Control Presence          3
Speed Limit (km/h)               91
Driver Age                       53
Driver Gender                     2
Driver License Status             2
Alcohol Involvement               2
Accident Location Details         4
dtype: int64

In [23]:
df['Traffic Control Presence'].unique()

<StringArray>
['Signs', 'Signals', 'Police Checkpost', nan]
Length: 4, dtype: str

In [24]:
df['Driver License Status'].unique()

<StringArray>
[nan, 'Valid', 'Expired']
Length: 3, dtype: str

In [27]:
df['Traffic Control Presence'] = df['Traffic Control Presence'].fillna('Unknown')
df['Traffic Control Presence'].unique()

<StringArray>
['Signs', 'Signals', 'Police Checkpost', 'Unknown']
Length: 4, dtype: str

In [28]:
df['Driver License Status'] = df['Driver License Status'].fillna('Unknown')
df['Driver License Status'].unique()

<StringArray>
['Unknown', 'Valid', 'Expired']
Length: 3, dtype: str